### PR TITLE
Two keys press support and QoL changes

### PR DESCRIPTION
**Pull request by Givikap120**
1) Added better "two button pressed" visualization with yellow crosses
2) Moved keyboard and mouse keys separation into a checkmark (was buttons before)
3) Added "Key 1 and 2" button to support adding two buttons click at the same time
4) Changed hotkeys to be more convenient (and added 4 new)
5) Moved "None key press" button by 1px to be inline with others

### CODE REVIEW

**Comment by thebetioplane** [comment]
Looks fine, if you don't mind could you also update distro_aux/README.md with the new keybindings? That is the readme that gets deployed with the release.

**Comment by Givikap120** [comment]
> Looks fine, if you don't mind could you also update distro_aux/README.md with the new keybindings? That is the readme that gets deployed with the release.

Can I somehow contact you? I need some questions to ask.

**Comment by thebetioplane** [comment]
> Can I somehow contact you? I need some questions to ask.

I'll send you an email.

**Comment by Givikap120** [comment]
Hello, i've made the functionality about moving frames in time, adding new
ones and deleting
[image: изображение_2023-08-07_185650651.png]
But idk where and how it should be put. Also, when i've thought about "add
new frame" implementation, i thought about slider from 1 to "time to next
frame" in UI but idk how to directly bind max value in slider to c++ dll so
i'm just putting this new frame in the middle between two frames (Mark In
and next to Mark In).

The reason why i'm not putting this in a pull request - it's because your
project is bugging in my VS. It just changes all sizes in UI when i'm open
it. It was very painful to change it back in first pull request, and i
don't wanna to do it again. Do you have any ideas how to overcome this? And
also, the volume slider is bugged because of this.
[image: image.png]

**Comment by thebetioplane** [comment]
Sorry for not responding it looks like your comment was marked off topic by Github (?) so I didn't see it (some sort of auto-moderation?).

I'll merge the PR now, thank you for contributing. Unfortunately I am unsure how to help fix your Visual Studio, I am using version 2022 community, if you are on an earlier version you can try upgrading?

For part 1 of your question, I am unsure what you are asking.

**Comment by Givikap120** [comment]
> Sorry for not responding it looks like your comment was marked off topic by Github (?) so I didn't see it (some sort of auto-moderation?).
> 
> I'll merge the PR now, thank you for contributing. Unfortunately I am unsure how to help fix your Visual Studio, I am using version 2022 community, if you are on an earlier version you can try upgrading?
> 
> For part 1 of your question, I am unsure what you are asking.

I've added a lot of features, but it will require interface fixing from you because of this broken thing

**Pull request merged**
